@c getstart.texi

@c This file is part of the GNU 3DLDF User Manual.
@c Copyright (C) 2013 The Free Software Foundation
@c See the section "GNU Free Documentation License" in the file 
@c fdl.texi for copying conditions.

@c * (1)

@node Getting Started, Examples, Invoking, Top
@chapter Getting Started

@menu
* Data Types and Declarations::
@end menu

@c ** (2) Data Types and Declarations

@node Data Types and Declarations, , , Getting Started
@section Data Types and Declarations

@c Local Variables:
@c abbrev-mode:t
@c eval:(outline-minor-mode t)
@c eval:(auto-fill-mode t)
@c End:
 


