@c intro.texi, , Top, Top

@c This file is part of the 3DLDF User Manual.
@c Copyright (C) 2013 The Free Software Foundation
@c See the section "GNU Free Documentation License" in the file 
@c fdl.texi for copying conditions.

@c * (1) Introduction

@node  Introduction, Installation, , Top
@chapter Introduction

@c ** (2)

@c * (1)

@c Local Variables:
@c mode:Texinfo
@c abbrev-mode:t
@c eval:(outline-minor-mode t)
@c outline-regexp:"@c *\\*+"
@c eval:(set (make-local-variable 'run-texi2dvi-on-file) "gwrdifpk.texi")
@c End:
