b@c /home/laurence/3DLDF-2.0.4/doc/paths.texi

@c Created by Laurence D. Finston (LDF) Sun 04 Apr 2021 01:22:29 PM CEST

@c This file is part of the 3DLDF 3.0 User Manual.
@c Copyright (C) 2021 The Free Software Foundation

@c See the section "GNU Free Documentation License" in the file 
@c fdl.texi for copying conditions.

@c Author:  Laurence D. Finston (LDF)

@c * (1) Paths

@node Paths
@chapter Paths

@c ** (2)

@c * (1) Local Variables for Emacs

@c For use in indirect buffers:
@c
@c (progn (texinfo-mode) (outline-minor-mode t) (setq outline-regexp "@c *\\*+") (ignore (quote 
@c )) (set (make-local-variable 'run-texi2dvi-on-file) "3dldf.texi"))
  
@c Local Variables:
@c mode:Texinfo
@c abbrev-mode:t
@c eval:(outline-minor-mode t)
@c outline-regexp:"@c *\\*+"
@c eval:(set (make-local-variable 'run-texi2dvi-on-file) "3dldf.texi")
@c fill-column:80
@c End:


