@node Using 3DLDF, Points, Contributing to 3DLDF, Top
@chapheading Using 3DLDF
 
Since 3DLDF does not yet have an input routine, user code must be
written in @cpp{} (in @file{main.web}, or some other file) and compiled.
Then, 3DLDF must be relinked, together with the new file of object
code resulting from the compilation.  
For now, the important point is that the text of
the examples in this manual represent @cpp{} code.
@xref{Installing and Running 3DLDF}, for more information. 
